model_list:
  - model_name: groq/*
    litellm_params:
      model: groq/*

  - model_name: nvidia_nim/*
    litellm_params:
      model: nvidia_nim/*

  - model_name: openai/*
    litellm_params:
      model: openai/*

  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*

  - model_name: gemini/*
    litellm_params:
      model: gemini/*

  - model_name: ollama/*
    litellm_params:
      model: ollama/*

litellm_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
